# Generated by Django 5.0.6 on 2024-06-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="followers",
            new_name="follower",
        ),
    ]
